version: '3.3'

services:
    pimpcraft:
        image: ${METABOCRAFT_IMAGE-metabocraft:latest}
        build: .
        ports:
            - "${EXTERNAL_PORT-80}:32909"
            - "25565:25565"
        command: ./start_docker.sh